mydata <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactor=FALSE)
mydata$Date <- as.Date(mydata$Date, "%d/%m/%Y")
mydata <- subset(mydata, mydata$Date>="2007-02-01" & mydata$Date<="2007-02-02")
dt <- paste(mydata$Date, mydata$Time, sep=" ")
mydata$DateTime <- as.POSIXlt(dt)
mydata$Global_active_power <- as.double(mydata$Global_active_power)
plot(mydata$DateTime, mydata$Global_active_power,ylab="Global Active Power (kilowatts)", xlab="",type='n')
lines(mydata$DateTime, mydata$Global_active_power)
dev.copy(png, file="plot2.png")
dev.off()